/**
 * HWstore — composant Seeder Script
 * Run: npx ts-node -r tsconfig-paths/register src/database/seed.ts
 * Uses existing TypeORM DB config from .env
 */
import 'reflect-metadata';
import { DataSource } from 'typeorm';
import * as dotenv from 'dotenv';
import * as path from 'path';

dotenv.config({ path: path.join(__dirname, '../../.env') });

const dataSource = new DataSource({
  type: 'postgres',
  host: process.env.DB_HOST ?? 'localhost',
  port: parseInt(process.env.DB_PORT ?? '5432'),
  username: process.env.DB_USERNAME ?? 'postgres',
  password: process.env.DB_PASSWORD ?? 'postgres',
  database: process.env.DB_DATABASE ?? 'hwstore',
  synchronize: false,
});

const composants = [
  // ── MOTHERBOARDS ─────────────────────────────────────────────
  {
    name: 'ASUS ROG STRIX B650E-F Gaming WiFi',
    slug: 'asus-rog-strix-b650e-f-wifi',
    brand: 'ASUS',
    price: 289.99,
    rating: 4.7,
    stock: 15,
    type: 'carte-mere',
    description: 'Carte mère AM5 DDR5 ATX avec WiFi 6E et PCIe 5.0',
    images: ['https://m.media-amazon.com/images/I/81nCiMOuQmL._AC_SL1500_.jpg'],
    specs: {
      socket: 'AM5',
      chipset: 'B650E',
      ramType: 'DDR5',
      maxRam: 128,
      pcieVersion: 5,
      formFactor: 'ATX',
      ramSlots: 4,
    },
    tags: {},
  },
  {
    name: 'MSI MAG X670E TOMAHAWK WiFi',
    slug: 'msi-mag-x670e-tomahawk-wifi',
    brand: 'MSI',
    price: 349.99,
    rating: 4.6,
    stock: 10,
    type: 'carte-mere',
    description: 'Carte mère haut de gamme AM5 X670E DDR5 ATX',
    images: ['https://m.media-amazon.com/images/I/81-VFcpXC7L._AC_SL1500_.jpg'],
    specs: {
      socket: 'AM5',
      chipset: 'X670E',
      ramType: 'DDR5',
      maxRam: 192,
      pcieVersion: 5,
      formFactor: 'ATX',
      ramSlots: 4,
    },
    tags: {},
  },
  {
    name: 'Gigabyte B650 AORUS Elite AX',
    slug: 'gigabyte-b650-aorus-elite-ax',
    brand: 'Gigabyte',
    price: 219.99,
    rating: 4.5,
    stock: 20,
    type: 'carte-mere',
    description: 'Carte mère AM5 B650 DDR5 ATX WiFi 6E',
    images: ['https://m.media-amazon.com/images/I/81wl7BQqe7L._AC_SL1500_.jpg'],
    specs: {
      socket: 'AM5',
      chipset: 'B650',
      ramType: 'DDR5',
      maxRam: 128,
      pcieVersion: 5,
      formFactor: 'ATX',
      ramSlots: 4,
    },
    tags: {},
  },
  {
    name: 'MSI PRO B760M-A WiFi DDR4',
    slug: 'msi-pro-b760m-a-wifi-ddr4',
    brand: 'MSI',
    price: 139.99,
    rating: 4.4,
    stock: 18,
    type: 'carte-mere',
    description: 'Carte mère Intel LGA1700 B760 Micro-ATX DDR4',
    images: ['https://m.media-amazon.com/images/I/71vHHXlREJL._AC_SL1500_.jpg'],
    specs: {
      socket: 'LGA1700',
      chipset: 'B760',
      ramType: 'DDR4',
      maxRam: 128,
      pcieVersion: 4,
      formFactor: 'Micro-ATX',
      ramSlots: 2,
    },
    tags: {},
  },
  // ── CPUs ─────────────────────────────────────────────────────
  {
    name: 'AMD Ryzen 7 9700X',
    slug: 'amd-ryzen-7-9700x',
    brand: 'AMD',
    price: 329.99,
    rating: 4.8,
    stock: 25,
    type: 'processeur',
    description: 'Processeur AMD Zen 5, 8 cœurs 16 threads, socket AM5',
    images: ['https://m.media-amazon.com/images/I/61SadPOFHnL._AC_SL1500_.jpg'],
    specs: {
      socket: 'AM5',
      cores: 8,
      threads: 16,
      tdp: 65,
      memorySupport: 'DDR5',
    },
    tags: {},
  },
  {
    name: 'AMD Ryzen 9 9900X',
    slug: 'amd-ryzen-9-9900x',
    brand: 'AMD',
    price: 449.99,
    rating: 4.9,
    stock: 12,
    type: 'processeur',
    description: 'Processeur AMD Zen 5 haut de gamme, 12 cœurs 24 threads',
    images: ['https://m.media-amazon.com/images/I/61SadPOFHnL._AC_SL1500_.jpg'],
    specs: {
      socket: 'AM5',
      cores: 12,
      threads: 24,
      tdp: 120,
      memorySupport: 'DDR5',
    },
    tags: {},
  },
  {
    name: 'AMD Ryzen 5 7600X',
    slug: 'amd-ryzen-5-7600x',
    brand: 'AMD',
    price: 199.99,
    rating: 4.5,
    stock: 30,
    type: 'processeur',
    description: 'Processeur AM5 entrée de gamme, 6 cœurs 12 threads DDR5',
    images: ['https://m.media-amazon.com/images/I/51MC78MSPKL._AC_SL1500_.jpg'],
    specs: {
      socket: 'AM5',
      cores: 6,
      threads: 12,
      tdp: 105,
      memorySupport: 'DDR5',
    },
    tags: {},
  },
  {
    name: 'Intel Core i7-14700K',
    slug: 'intel-core-i7-14700k',
    brand: 'Intel',
    price: 369.99,
    rating: 4.7,
    stock: 20,
    type: 'processeur',
    description: 'Processeur Intel LGA1700 20 cœurs 28 threads',
    images: ['https://m.media-amazon.com/images/I/61s3GNquO-L._AC_SL1500_.jpg'],
    specs: {
      socket: 'LGA1700',
      cores: 20,
      threads: 28,
      tdp: 125,
      memorySupport: 'DDR4',
    },
    tags: {},
  },
  {
    name: 'Intel Core i5-14600K',
    slug: 'intel-core-i5-14600k',
    brand: 'Intel',
    price: 259.99,
    rating: 4.6,
    stock: 28,
    type: 'processeur',
    description: 'Processeur Intel LGA1700 14 cœurs 20 threads',
    images: ['https://m.media-amazon.com/images/I/51cpbFVNLGL._AC_SL1500_.jpg'],
    specs: {
      socket: 'LGA1700',
      cores: 14,
      threads: 20,
      tdp: 125,
      memorySupport: 'DDR4',
    },
    tags: {},
  },
  // ── GPUs ─────────────────────────────────────────────────────
  {
    name: 'NVIDIA GeForce RTX 4080 Super 16Go',
    slug: 'nvidia-rtx-4080-super-16go',
    brand: 'NVIDIA',
    price: 999.99,
    rating: 4.9,
    stock: 8,
    type: 'gpu',
    description: 'Carte graphique NVIDIA Ada Lovelace 16GB GDDR6X PCIe 4.0',
    images: ['https://m.media-amazon.com/images/I/712h3kkPSCL._AC_SL1500_.jpg'],
    specs: {
      vram: 16,
      recommendedPsu: 750,
      lengthMm: 336,
      pcieVersion: 4,
      tdp: 320,
    },
    tags: {},
  },
  {
    name: 'NVIDIA GeForce RTX 4070 Ti Super 16Go',
    slug: 'nvidia-rtx-4070-ti-super-16go',
    brand: 'NVIDIA',
    price: 799.99,
    rating: 4.8,
    stock: 12,
    type: 'gpu',
    description: 'Carte graphique 16GB GDDR6X — excellent pour 4K',
    images: ['https://m.media-amazon.com/images/I/71L6TJU0J1L._AC_SL1500_.jpg'],
    specs: {
      vram: 16,
      recommendedPsu: 700,
      lengthMm: 317,
      pcieVersion: 4,
      tdp: 285,
    },
    tags: {},
  },
  {
    name: 'AMD Radeon RX 7900 XTX 24Go',
    slug: 'amd-rx-7900-xtx-24go',
    brand: 'AMD',
    price: 849.99,
    rating: 4.7,
    stock: 6,
    type: 'gpu',
    description: 'Carte graphique AMD RDNA 3 24GB GDDR6 PCIe 4.0',
    images: ['https://m.media-amazon.com/images/I/71AE8NBAXKL._AC_SL1500_.jpg'],
    specs: {
      vram: 24,
      recommendedPsu: 800,
      lengthMm: 287,
      pcieVersion: 4,
      tdp: 355,
    },
    tags: {},
  },
  {
    name: 'NVIDIA GeForce RTX 4060 Ti 8Go',
    slug: 'nvidia-rtx-4060-ti-8go',
    brand: 'NVIDIA',
    price: 399.99,
    rating: 4.5,
    stock: 22,
    type: 'gpu',
    description: 'Carte graphique 1080p/1440p PCIe 4.0 compact 8GB',
    images: ['https://m.media-amazon.com/images/I/71FPWv8NFFL._AC_SL1500_.jpg'],
    specs: {
      vram: 8,
      recommendedPsu: 550,
      lengthMm: 240,
      pcieVersion: 4,
      tdp: 160,
    },
    tags: {},
  },
  // ── RAM ──────────────────────────────────────────────────────
  {
    name: 'Corsair Vengeance DDR5-6000 32Go (2x16Go)',
    slug: 'corsair-vengeance-ddr5-6000-32go',
    brand: 'Corsair',
    price: 89.99,
    rating: 4.7,
    stock: 40,
    type: 'ram',
    description: 'Kit DDR5 6000MHz CL36 32Go — optimisé Ryzen AM5',
    images: ['https://m.media-amazon.com/images/I/71mWiMkCcVL._AC_SL1500_.jpg'],
    specs: { type: 'DDR5', speed: 6000, capacity: 16, sticks: 2 },
    tags: {},
  },
  {
    name: 'G.Skill Trident Z5 DDR5-6400 64Go (2x32Go)',
    slug: 'gskill-trident-z5-ddr5-6400-64go',
    brand: 'G.Skill',
    price: 159.99,
    rating: 4.8,
    stock: 18,
    type: 'ram',
    description: 'Kit DDR5 6400MHz CL32 64Go haut de gamme',
    images: ['https://m.media-amazon.com/images/I/71c1tJuq6XL._AC_SL1500_.jpg'],
    specs: { type: 'DDR5', speed: 6400, capacity: 32, sticks: 2 },
    tags: {},
  },
  {
    name: 'Corsair Vengeance DDR4-3200 16Go (2x8Go)',
    slug: 'corsair-vengeance-ddr4-3200-16go',
    brand: 'Corsair',
    price: 39.99,
    rating: 4.6,
    stock: 50,
    type: 'ram',
    description: 'Kit DDR4 3200MHz CL16 16Go — compatible Intel LGA1700',
    images: ['https://m.media-amazon.com/images/I/61n8wMiPlzL._AC_SL1500_.jpg'],
    specs: { type: 'DDR4', speed: 3200, capacity: 8, sticks: 2 },
    tags: {},
  },
  {
    name: 'Kingston Fury Beast DDR4-3600 32Go (2x16Go)',
    slug: 'kingston-fury-beast-ddr4-3600-32go',
    brand: 'Kingston',
    price: 64.99,
    rating: 4.5,
    stock: 35,
    type: 'ram',
    description: 'Kit DDR4 3600MHz CL17 32Go — polyvalent Intel DDR4',
    images: ['https://m.media-amazon.com/images/I/81lgmTb-pOL._AC_SL1500_.jpg'],
    specs: { type: 'DDR4', speed: 3600, capacity: 16, sticks: 2 },
    tags: {},
  },
  // ── PSUs ─────────────────────────────────────────────────────
  {
    name: 'be quiet! Dark Power 13 1000W Titanium',
    slug: 'bequiet-dark-power-13-1000w',
    brand: 'be quiet!',
    price: 259.99,
    rating: 4.9,
    stock: 10,
    type: 'alimentation',
    description: 'Alimentation 1000W modulaire 80+ Titanium ultra-silencieuse',
    images: ['https://m.media-amazon.com/images/I/61v1Pz9rRaL._AC_SL1500_.jpg'],
    specs: { wattage: 1000, efficiency: 'Titanium' },
    tags: {},
  },
  {
    name: 'Corsair RM850x 850W 80+ Gold',
    slug: 'corsair-rm850x-850w-gold',
    brand: 'Corsair',
    price: 149.99,
    rating: 4.8,
    stock: 20,
    type: 'alimentation',
    description: 'Alimentation 850W modulaire 80+ Gold — fiable et silencieuse',
    images: ['https://m.media-amazon.com/images/I/71DY7s0BNCL._AC_SL1500_.jpg'],
    specs: { wattage: 850, efficiency: 'Gold' },
    tags: {},
  },
  {
    name: 'Seasonic Focus GX-750 80+ Gold',
    slug: 'seasonic-focus-gx-750-gold',
    brand: 'Seasonic',
    price: 119.99,
    rating: 4.7,
    stock: 25,
    type: 'alimentation',
    description: 'Alimentation 750W modulaire 80+ Gold',
    images: ['https://m.media-amazon.com/images/I/71UKRqkiGzL._AC_SL1500_.jpg'],
    specs: { wattage: 750, efficiency: 'Gold' },
    tags: {},
  },
  {
    name: 'EVGA SuperNOVA 650 G6 80+ Gold',
    slug: 'evga-supernova-650-g6-gold',
    brand: 'EVGA',
    price: 89.99,
    rating: 4.5,
    stock: 30,
    type: 'alimentation',
    description: 'Alimentation 650W compacte 80+ Gold — idéale RTX 4060 Ti',
    images: ['https://m.media-amazon.com/images/I/71MGPV8YiZL._AC_SL1500_.jpg'],
    specs: { wattage: 650, efficiency: 'Gold' },
    tags: {},
  },
  // ── CASES ────────────────────────────────────────────────────
  {
    name: 'Fractal Design Torrent ATX',
    slug: 'fractal-design-torrent-atx',
    brand: 'Fractal Design',
    price: 189.99,
    rating: 4.8,
    stock: 14,
    type: 'boitier',
    description: "Boîtier ATX haute airflow — GPU jusqu'à 461mm",
    images: ['https://m.media-amazon.com/images/I/61ZZWZB5kYL._AC_SL1500_.jpg'],
    specs: {
      maxGpuLength: 461,
      supportedFormFactors: ['ATX', 'Micro-ATX', 'Mini-ITX'],
      maxCpuCoolerHeight: 188,
    },
    tags: {},
  },
  {
    name: 'Lian Li Lancool 216',
    slug: 'lian-li-lancool-216',
    brand: 'Lian Li',
    price: 109.99,
    rating: 4.7,
    stock: 20,
    type: 'boitier',
    description: 'Boîtier ATX airflow 2 ventilateurs 160mm inclus',
    images: ['https://m.media-amazon.com/images/I/71AsTXifCpL._AC_SL1500_.jpg'],
    specs: {
      maxGpuLength: 435,
      supportedFormFactors: ['ATX', 'Micro-ATX', 'Mini-ITX'],
      maxCpuCoolerHeight: 176,
    },
    tags: {},
  },
  {
    name: 'NZXT H5 Flow Compact ATX',
    slug: 'nzxt-h5-flow-compact',
    brand: 'NZXT',
    price: 99.99,
    rating: 4.6,
    stock: 18,
    type: 'boitier',
    description: 'Boîtier ATX panneaux perforés — GPU max 365mm',
    images: ['https://m.media-amazon.com/images/I/51a2ZcunfOL._AC_SL1500_.jpg'],
    specs: {
      maxGpuLength: 365,
      supportedFormFactors: ['ATX', 'Micro-ATX'],
      maxCpuCoolerHeight: 165,
    },
    tags: {},
  },
  {
    name: 'Cooler Master MasterBox Q300L Micro-ATX',
    slug: 'coolermaster-masterbox-q300l',
    brand: 'Cooler Master',
    price: 59.99,
    rating: 4.3,
    stock: 25,
    type: 'boitier',
    description: 'Boîtier Micro-ATX compact budget — GPU max 360mm',
    images: ['https://m.media-amazon.com/images/I/71WF1DLRJJL._AC_SL1500_.jpg'],
    specs: {
      maxGpuLength: 360,
      supportedFormFactors: ['Micro-ATX', 'Mini-ITX'],
      maxCpuCoolerHeight: 157,
    },
    tags: {},
  },
  // ── COOLERS ──────────────────────────────────────────────────
  {
    name: 'Noctua NH-D15 chromax.black',
    slug: 'noctua-nh-d15-chromax-black',
    brand: 'Noctua',
    price: 99.99,
    rating: 4.9,
    stock: 20,
    type: 'refroidissement',
    description: 'Ventirad tour double — meilleur air cooler du marché',
    images: ['https://m.media-amazon.com/images/I/71i9tFKMLLL._AC_SL1500_.jpg'],
    specs: {
      supportedSockets: ['AM5', 'AM4', 'LGA1700', 'LGA1200', 'LGA1151'],
      tdpRating: 250,
      heightMm: 165,
    },
    tags: {},
  },
  {
    name: 'be quiet! Dark Rock Pro 4',
    slug: 'bequiet-dark-rock-pro-4',
    brand: 'be quiet!',
    price: 79.99,
    rating: 4.7,
    stock: 15,
    type: 'refroidissement',
    description: 'Ventirad tour double ultra-silencieux 250W TDP',
    images: ['https://m.media-amazon.com/images/I/61JEgm8bYiL._AC_SL1500_.jpg'],
    specs: {
      supportedSockets: ['AM5', 'AM4', 'LGA1700', 'LGA1200', 'LGA1151'],
      tdpRating: 250,
      heightMm: 162,
    },
    tags: {},
  },
  {
    name: 'Arctic Liquid Freezer III 360mm AIO',
    slug: 'arctic-liquid-freezer-iii-360',
    brand: 'Arctic',
    price: 139.99,
    rating: 4.8,
    stock: 18,
    type: 'refroidissement',
    description: 'Watercooling AIO 360mm — performances haut de gamme',
    images: ['https://m.media-amazon.com/images/I/71j0R6BDRHL._AC_SL1500_.jpg'],
    specs: {
      supportedSockets: ['AM5', 'AM4', 'LGA1700', 'LGA1200'],
      tdpRating: 300,
      heightMm: 27,
    },
    tags: {},
  },
  {
    name: 'DeepCool AK620 Zero Dark',
    slug: 'deepcool-ak620-zero-dark',
    brand: 'DeepCool',
    price: 54.99,
    rating: 4.6,
    stock: 30,
    type: 'refroidissement',
    description: 'Ventirad tour double 260W TDP — rapport qualité/prix',
    images: ['https://m.media-amazon.com/images/I/71qL3TqY3pL._AC_SL1500_.jpg'],
    specs: {
      supportedSockets: ['AM5', 'AM4', 'LGA1700', 'LGA1200', 'LGA1151'],
      tdpRating: 260,
      heightMm: 160,
    },
    tags: {},
  },
  // ── STORAGE ──────────────────────────────────────────────────
  {
    name: 'Samsung 990 Pro 2To NVMe PCIe 4.0',
    slug: 'samsung-990-pro-2to-nvme',
    brand: 'Samsung',
    price: 149.99,
    rating: 4.9,
    stock: 35,
    type: 'stockage',
    description: 'SSD NVMe M.2 2To — 7450 Mo/s lecture',
    images: ['https://m.media-amazon.com/images/I/61BVBKJHNML._AC_SL1500_.jpg'],
    specs: {
      storageType: 'NVMe',
      capacity: 2000,
      readSpeed: 7450,
      writeSpeed: 6900,
    },
    tags: {},
  },
  {
    name: 'WD Black SN850X 1To NVMe PCIe 4.0',
    slug: 'wd-black-sn850x-1to-nvme',
    brand: 'Western Digital',
    price: 89.99,
    rating: 4.8,
    stock: 40,
    type: 'stockage',
    description: 'SSD NVMe 1To 7300 Mo/s — idéal gaming',
    images: ['https://m.media-amazon.com/images/I/71SEV2RDYNL._AC_SL1500_.jpg'],
    specs: {
      storageType: 'NVMe',
      capacity: 1000,
      readSpeed: 7300,
      writeSpeed: 6300,
    },
    tags: {},
  },
  {
    name: 'Seagate Barracuda 2To HDD 7200RPM',
    slug: 'seagate-barracuda-2to-hdd',
    brand: 'Seagate',
    price: 49.99,
    rating: 4.3,
    stock: 60,
    type: 'stockage',
    description: 'Disque dur 2To 7200RPM — stockage secondaire',
    images: ['https://m.media-amazon.com/images/I/71WM+YMFxwL._AC_SL1500_.jpg'],
    specs: {
      storageType: 'HDD',
      capacity: 2000,
      readSpeed: 190,
      writeSpeed: 190,
    },
    tags: {},
  },
];

async function seed() {
  await dataSource.initialize();
  console.log('✅ Connected to database');

  let inserted = 0;
  let skipped = 0;

  for (const comp of composants) {
    const existing = await dataSource.query(
      `SELECT id FROM composants WHERE slug = $1`,
      [comp.slug],
    );
    if (existing.length > 0) {
      console.log(`⏭  Skipped (already exists): ${comp.name}`);
      skipped++;
      continue;
    }

    await dataSource.query(
      `INSERT INTO composants
        (name, slug, brand, price, rating, images, type, description, specs, tags, stock)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,
      [
        comp.name,
        comp.slug,
        comp.brand,
        comp.price,
        comp.rating,
        `{${comp.images.map((i) => `"${i}"`).join(',')}}`,
        comp.type,
        comp.description,
        JSON.stringify(comp.specs),
        JSON.stringify(comp.tags),
        comp.stock,
      ],
    );
    console.log(`✅ Inserted: ${comp.name}`);
    inserted++;
  }

  await dataSource.destroy();
  console.log(`\n🎉 Done — ${inserted} inserted, ${skipped} skipped.`);
}

seed().catch((err) => {
  console.error('❌ Seed failed:', err.message);
  process.exit(1);
});
